"use strict ";
const axios = require ("axios") ;
const apikey = "efd0c606406c76609e3105eb168ebbbb"; // your api key to the api generated bythe website

const getCurrentWeather = async location => {
    return new Promise ( async ( resolve , reject ) => {
        try {
            const weatherConditions = await axios.get(
                "https://api.openweathermap.org/data/2.5/weather",
            // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json " ,
    {
        params : {
            appId: apikey ,
            q: location,
            units: "metric"
        }
    }) ;

    resolve ( weatherConditions.data ) // returns back the results to the chatbot
}
catch ( error ) {
        console.log(error)
    }
}) ;
}

const getWeatherForecast = async (location) => {
    return new Promise ( async ( resolve , reject ) => {
        try {
            const weatherConditions = await axios.get(
                "http://api.openweathermap.org/data/2.5/forecast",
                // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json " ,
                {
                    params : {
                        appId: apikey ,
                        q: location,
                        cnt:25,
                        units: "metric"
                    }
                }) ;

            resolve ( weatherConditions.data ) // returns back the results to the chatbot
        }
        catch ( error ) {
            console.log(error)
        }
    }) ;
}



module.exports = {getCurrentWeather,getWeatherForecast} ;
